validates:
  maximum_name: 50
  maximum_email: 255
  minimum_pass: 6
  maximum_content: 140
helper:
  size: 80
  one: "1"
layout:
  per_page: 10
  user:
    size: 50
time_expire: 2
micropost:
  img_size: 5
  accept_img: "image/jpeg,image/gif,image/png"
